version: "2"

services:

  web:
    hostname: 'sy-app'
    container_name : sy-app
    build: sy-compose
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    links:
      - database:database
    working_dir: /app
    restart: always
    networks:
      sy_net:
        ipv4_address: 172.16.238.15
        ipv6_address: 2001:3984:3989::15

  database:
    hostname: 'sy-db'
    container_name : sy-db
    image: postgres:9.4
    volumes:
      - ./.dump:/var/lib/postgresql/data
      - ./recover/back:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=sy
      - POSTGRES_DB=sy
      - COMPOSE_PROJECT_NAME=sy-db
#    ports:
#      - "5432:5432"
    networks:
      sy_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  sy_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1